### ISSUE TITLE
TODO list for v5.5 release

### ISSUE THREAD

**Issue by onebone** [onebone/EconomyS#80]
- [x] Remove bank feature
- [x] Remove debt feature
- [x] Add usury feature by seperated plugin
 - [x] Calculate time on server stop
 - [x] Implement list command to see requester and host list
 - [x] Calculate interest
 - [x] Implement money and paying
 - [x] Show client list of host
 - [x] Show list of host where client joined
 - [x] Implement determining due by command

**Comment by vvzar** [comment]
Why are You removing bank? We already using it :(

**Comment by onebone** [comment]
@vvzar Player are abusing bank system with interest system. Since most of servers are blocking the bank system, the system is better to be removed.

**Comment by ChalkPE** [comment]
- [ ] Compatibility for API 1.12.0

**Comment by 64FF00** [comment]
@ChalkPE Ye

**Comment by iVertx** [comment]
@onebone Any word about implementing MySQL on EconomyAPI, or making the money file be unique for each player? because i'm setting up a really big network and i'm using MySQL for make some features be avaliable in all servers, money is the first thing that i need... I want that if the player earn money on server a, these money be availiable on server b, with MySQL or individual files i can do that... please consider think about that...

**Comment by 64FF00** [comment]
@iVertx No clue about it, hehehe. But he said he would add it in the future.

**Comment by jasonwynn10** [comment]
https://github.com/LostTeam/EconomySMySQL
